# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo::migrator"
    cpp_includes:
        - "mongo/db/pipeline/aggregation_request_helper.h"
        - "mongo/db/query/count_request.h"
        - "mongo/db/query/explain_options.h"
imports:
    - "mongo/idl/basic_types.idl"

types:
    pipeline:
        bson_serialization_type: any
        description: "An array of objects specifying the aggregation pipeline."
        cpp_type: "std::vector<mongo::BSONObj>" 
        deserializer: ::mongo::parsePipelineFromBSON

structs:
    AggregateFromOracleReply:
        description: "results of aggregating from oracle"
        fields:
            firstBatch:
                description: "The batch of resulting documents"
                type: array<object>


commands:
    aggregateFromOracle:
        description: "Represents the options for running an aggregation from an Oracle database"
        cpp_name: AggregateFromOracleCommand
        command_name: aggregateFromOracle
        strict: true
        namespace: concatenate_with_db
        api_version: 2
        reply_type: AggregateFromOracleReply
        fields:
            pipeline:
                description: "An unparsed version of the pipeline"
                type: pipeline
            username:
                description: "Username to authenticate to oracle with"
                type: string
            password:
                description: "Password to authenticate to oracle with"
                type: string
            connectionString:
                description: "Connection string to connect to oracle with"
                type: string
            query:
                description: "SQL query to run against oracle"
                type: string
